[team02-BE] TO-DO 리스트 프로젝트 1주차 PR 드립니다.
codesquad-members-2021/todo-list pull request #12
Opened 2021-04-09 17:10 UTC by janeljs

안녕하세요, 로빈 & 제인입니다🙂 처음해보는 프로젝트라 Spring Data JDBC, JWT, 인터셉터 등을 활용하는 법을 공부하고 기능을 구현하는데 초점을 맞춰 진행했습니다. 아직 리팩토링은 진행하지 않은 상태인데, 부족한 부분은 리뷰 남겨주시면 적극 반영하겠습니다.

## 구현 사항
- Spring Data JDBC를 통한 DB 연동
- 회원가입 기능 구현
- 로그인 기능 구현
- 카드 삭제 기능 구현
- 카드 수정 기능 구현
- JWT, 인터셉터를 활용한 인증 구현

+) 팀 내에서 Card가 User를 가지고 있는 형태로 Mock API를 정의했었는데, Card 내에 user_id로 JPA처럼 User 객체를 어떻게 가져올 수 있을지 고민입니다. 

소중한 시간을 내어 리뷰해주셔서 감사합니다!

2021-04-10 04:41 UTC, wheejuni requested changes
고민하고 있는 부분은 쉽게 말해 양방향 매핑 + lazy loading을 Spring Data JDBC에서 어떻게 구현할지 고민하시는 것으로 보입니다.
현재 그런 기능은 Spring Data JDBC에서 지원하지 않는 것으로 보이지만, [After Load Event](https://docs.spring.io/spring-data/jdbc/docs/1.0.2.RELEASE/api/org/springframework/data/relational/core/mapping/event/AfterLoadEvent.html)를 캡쳐해서 비슷한 동작을 하도록 흉내내는 것이 유일한 솔루션으로 보입니다.

쉽게 말해 엔티티가 로드된 시점에 `userId` 필드를 훑고 `UserRepository.findById()` 를 호출해 정보를 주입시키는 방법입니다. 
이 구현을 위해선 Spring Framework의 `ApplicationEvent` 와 `ApplicationEventListener` 에 대한 이해가 있어야 하는데요, 모든 것을 이해하면 좋겠지만, 프로젝트 진행간에 그러기에는 너무 시간이 촉박하므로 일단 [이 글](https://brunch.co.kr/@springboot/422)을 참고해 보시는 것이 좋겠군요.

수고 많으셨습니다. 프로젝트 완성까지 힘내주세요! 💯

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/ApiResponse.java
> +    private Object data;
단순히 `Object` 타입을 넣는 것은 추후에 Jackson과 사용할때 호환성이 좋지 않을 것 같은 느낌인데요.
각 DTO가 따로 설계되어야 할 것 같습니다.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +    private UserService userService;
한 쪽은 `@Autowired` 를 사용하고 한 쪽은 `@Resource` 를 사용하신 이유가 있나요?

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +            Cookie[] cookies = request.getCookies();
JWT를 사용하는 것의 가장 큰 이점은 애플리케이션의 무상태성을 유지할 수 있다는 건데요, 
물론 세션이 만들어지지 않았으므로 엄밀히 말하면 지금 구현에서도 무상태성이 유지되는 방향이기는 합니다만, 보통 `Authorization` 헤더를 통해 JWT 토큰 정보를 주고받는 것이 흔한 설계입니다. 

지금처럼 쿠키를 통해 JWT를 관리하면 사용자가 쉽게 JWT토큰 정보를 취득할 수 있다는 점도 염두에 둬야 합니다. 
즉각적인 보안 위협이 되진 않겠지만 잠재적으론 충분한 리스크가 됩니다.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
> +                .sign(Algorithm.HMAC256(SECRET_KEY));
아무런 claim도 없이 단순히 토큰을 생성만 하고 있는데요, 
유저 ID(DB상의 PKEY로써의 ID), 유저의 권한 정도는 갖고 있는 것이 좋습니다. 
API 접근이 발생할 때마다 추가 인증 절차가 발생하지 않도록요.
추가 인증이 발생하더라도, DB에 부담을 최대한 줄일 수 있는, 좋은 성능을 갖는 key가 JWT안에 담겨 있어야 그 키를 통해 빠르게 사용자 정보를 찾고, DB에 가해지는 부하를 줄일 수 있습니다. 

애플리케이션의 스펙이 복잡해지고 기능이 고도화될수록 API 호출이 늘어나고, 그에 따라 JWT기반 인증 절차의 호출도 계속 늘어날 것임을 항상 고려해야 합니다.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    }
`HandlerMethodArgumentResolver` 기반으로 구현해주세요. 
[이 글](https://velog.io/@kingcjy/Spring-HandlerMethodArgumentResolver%EC%9D%98-%EC%82%AC%EC%9A%A9%EB%B2%95%EA%B3%BC-%EB%8F%99%EC%9E%91%EC%9B%90%EB%A6%AC) 을 참고해보시면 좋을 것 같네요. 이 경우 외에도, 앞으로 컨트롤러의 메소드에서 직접 사용할, 사용자의 요청에서 꺼내올 정보가 있다면 같은 방법으로 구현해주세요.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +        System.out.println("user: " + user.toString());
`logger` 선언해서 사용해주시고 컴포넌트 내에서 `.println()` **사용 금지** 입니다.
이유에 대해서 알아보시는 시간을 가져도 좋을 것 같군요.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    public final UserRepository userRepository;
아직 `Service` 는 구현되지 않은 거죠?

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
> +    }
빈 생성자라면 굳이 한 줄을 띄워야 할 필욘 없을 것 같아요.

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
> +    @Id
여기엔 한 줄 비워놓으면 좋을 것 같네요.

```suggestion
public class Card {
    
    @Id

2021-04-10 04:41 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/domain/User.java
> +    private List<Card> cards = new LinkedList<>();
`@MappedCollection` 사용하셔서 잘 표현해주신 것 같습니다. 
다만 반대쪽 `Card` 에 `user_id` 를 설정할 수 있는 편의 메소드가 구현돼있다면 더 깔끔하게 구현이 가능하지 않을까 싶습니다. 

```java
public void setOwnerUser(User user) {
    this.userId = user.getUserId();
}
```

다음과 같이 `~Ref` 클래스를 만들어서 참조 관계를 만들기 위해 사용하는 경우도 흔합니다.

```java
public class UserRef {
    private Long userId;
...
}
```

어느쪽이 더 편할지 판단하셔서 사용하시면 됩니다.

2021-04-14 09:22 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/ApiResponse.java
> +    private Object data;
CardDTO, CategoryDTO, HistoryDTO 등을 따로 정의해주었습니다!

2021-04-14 09:34 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +    private UserService userService;
이유는 잘 모르겠는데 JwtAuthInterceptor 내부에서 JwtUtil은 `@Autowired`로 잘 주입이 되는데 UserService는 주입이 되지 않는 문제가 발생하였습니다. 로빈과 함께 stack overflow를 참고하여 해당 어노테이션을 리소스로 고치고 JwtAuthInterceptor를 `@Component` 애노테이션이 아닌 WebConfig 내부에서 `@Bean`으로 등록해주는 방식으로 바꿨더니 잘 작동하더라구요... `@Resource`와 `@Autowired` 작동 방식에는 차이가 없는 것 같은데 왜 다르게 작동하는지 잘 모르겠습니다ㅠㅠ 
```
    @Bean
    public JwtAuthInterceptor jwtAuthInterceptor() {
        return new JwtAuthInterceptor();
    }
```

2021-04-14 09:34 UTC, malaheaven commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +    private UserService userService;
😢

2021-04-14 09:38 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +            Cookie[] cookies = request.getCookies();
Authorization 헤더를 통해 JWT 토큰 정보를 전달하고 싶었는데, 그렇게 처리할 경우 클라이언트에서 request header에 토큰 정보를 담아주지 않으면 인터셉터에서 토큰을 verify하지 못하는 문제가 발생했습니다. 로빈과 함께 검색하고 백엔드 반 팀원들에게도 물어본 결과, 저희가 response header에 담아준 토큰을 클라이언트 쪽에서 다시 헤더에 보내주어야 되는 것 같은데 맞나요? 백엔드 내부에서 response header로 보낸 토큰값을  request header에 담아주는 방법을 몰라 임시 방편으로 쿠키를 사용하였는데, 다른 방법이 있으면 알려주시면 감사하겠습니다!

2021-04-14 09:38 UTC, malaheaven commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +            Cookie[] cookies = request.getCookies();
😭

2021-04-14 09:46 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
> +                .sign(Algorithm.HMAC256(SECRET_KEY));
User name을 unique하게 설정한 뒤, 클레임으로 넣어 토큰을 생성하는 방식으로 변경하였습니다! name을 넣어주지 않아 토큰을 디코딩할 때 NPE가 뜨는 거였더라구요😅

2021-04-14 09:46 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
> +                .sign(Algorithm.HMAC256(SECRET_KEY));
이렇게 변경하니 user에 token 정보를 저장할 필요가 없어 해당 필드 또한 삭제하였습니다!

2021-04-14 10:37 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    }
HandlerMethodArgumentResolver를 사용하는 방식으로 리팩토링해보았습니다! HttpServletResponse로 받아오는 요청은 resolver를 사용하지 않아도 되나요?

2021-04-14 10:37 UTC, malaheaven commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    }
❓

2021-04-14 10:42 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +        System.out.println("user: " + user.toString());
.println()을 사용하면 IO 리소스를 많이 사용하여 시스템이 느려질 수 있기 때문일까요..?

2021-04-14 10:42 UTC, malaheaven commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +        System.out.println("user: " + user.toString());
❓  😢

2021-04-14 11:10 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    public final UserRepository userRepository;
넵! 아직도 완전히 리팩토링이 되지 않았지만 서비스 클래스를 추가해보았습니다!

2021-04-14 11:10 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
> +    }
해당 부분 수정했습니다!

2021-04-14 11:11 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
> +    @Id
수정한 뒤 푸쉬하였습니다! 자잘하게 컨벤션(?) 지키지 못한 부분이 많네요

2021-04-14 11:17 UTC, janeljs commented
@wheejuni 안녕하세요 브라이언! 로빈 & 제인입니다.
첫 프로젝트인 만큼 모든 과정을 페어 프로그래밍으로 진행하였고, 상의해서 답변을 남겼는데 아직 잘 모르겠는 부분들이 있어 코멘트로 질문들 남겼습니다🙂
보시고 피드백 부탁드립니다! 감사합니다🥰

2021-04-14 11:25 UTC, janeljs commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    }
HandlerMethodArgumentResolver를 사용하는 이점을 정확히 모르겠는데, 중복 코드를 제거하는 것 이외의 장점이 있나요?🤔

2021-04-15 09:47 UTC, janeljs commented
기능이 추가되어 많이 푸쉬가 되어버렸는데 해당 부분들은 2번째 pr에서 리뷰받을게요! 수정내역을 확인하기 어려우실 것 같아 죄송합니다😭 

그리고 mapped collection을 사용했던 부분은 iOS와 이야기한 결과 유저가 카드를 가지고 있을 필요가 없어 삭제했습니다! 

ApplicationEvent부분은 적용을 하지 못했는데 브라이언의 코멘트를 참고하여 서비스 계층에서 findById로 찾아 넣어줬습니다... 추후에 적용할 수 있으면 적용해볼게요! 

감사합니다.

2021-04-15 11:19 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +    private UserService userService;
신기한 현상이네요. 
이런 경우 생성자 주입으로 바꿔보면 컴포넌트간 의존관계가 더 단순하게 파악이 가능하고, 디버깅도 쉬울 텐데요. 한번 시도해보시는 건 어떨까요?

2021-04-15 11:21 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
> +            Cookie[] cookies = request.getCookies();
@janeljs 당연히 헤더 방식의 인증이라면 헤더에 토큰값이 담겨있어야겠죠. ㅎㅎㅎㅎ
이건 백엔드에서 처리될 로직은 아닙니다. 보통 API 명세에 헤더에 부여돼야 할 값을 명세하는 경우가 많은데요, 그 부분에서 `Authorization` 헤더로 이런 내용이 들어와야한다는 점을 명확히 부여해놓으면 클라이언트 개발자들도 쉽게 파악하고 개발할 수 있을 겁니다.

2021-04-15 11:23 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +    }
@janeljs `HttpServletRequest` 이겠죠? 이 클래스가 컨트롤러에서 사용돼야할 필요가 있을까요?
애플리케이션의 각 컴포넌트를 작성할 때는 서로 다른 레이어에 대한 의존성을 줄여야 한다고 생각합니다.
제가 `Service` 에서 `HttpSession` 을 파라메터로 받지 말라고 가이드한 내용을 기억하실 것입니다. 같은 맥락입니다.

2021-04-15 11:23 UTC, wheejuni commented on backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
> +        System.out.println("user: " + user.toString());
애플리케이션이 배포되는 장소(?) 나 프로필에 따라서 콘솔 노출 여부를 결정하는 기능이 `.println()` 에 있나요?
짧은 말로는 로깅 레벨이라고 하던데...

2021-04-15 11:27 UTC, wheejuni commented
@janeljs 수고 많으셨습니다. 일단 진행에는 큰 문제가 없을 것 같아 머지합니다.

2021-04-15 11:27 UTC, merged