[BE]Team-06: To-Do-List #1
codesquad-members-2021/todo-list pull request #15
Opened 2021-04-10 09:33 UTC by bong6981

안녕하세요. 6팀(BE)의 Shion과 Bongf입니다. 

### 1. 구현 내용 

- Card와 Action 클래스를 만들어 각각의 기능을 구현했습니다. 
- Card의 read, create, move, update, delete 의 기능을 만들고 해당 기능이 발생될 때마다 그 정보를 DB Action  테이블에 저장합니다. 
- Card의 칼럼과 Action의 타입을 Enum으로 구현했습니다. 
- Spring Data JDBC를 MySQL과 연동했습니다. 

### 2. 고민한 부분 

- (1) URL
    - CardController에서 move와 update의 메소드를 나눴지만 둘 다 동일한 URL로 매핑("@PutMappint("/")")되는 문제가 발생, URL을 기능에 따라 명시적으로 구분하기 위해 URL에 "move", "update"를 포함시켰습니다. 
    - 통일성을 위해 다른 url에도 "create", "delete"를 포함시켰습니다. 
    - REST API에 어긋나지만 기능 구분을 위해 필요한 것 같아 위와 같이 적용했습니다. 

- (2) DTO 
    - 처음에 Action 객체에 Card 객체를 넣어주려고 했습니다. 
    - 그러나 Action 객체에 Card 객체가 필드로 들어가면 MySQL에 테이블이 생성되지 않아 
    - Card의 Id만 필드로 설정했습니다. 
    - ActionsReponseDto를 만들어 Action 필드에 작성된 Card Id로 해당 Card의 Title을 가져와 반환하고자 하였으나 
    - Dto의 개념이 다른 Entity에서 정보를 가져와 가공하면 안되지 않을까 하는 고민으로 Action에는 Card의 title을 넣어주는 것으로 수정했습니다. 

코드 리뷰 감사하다는 말씀 드립니다.!

2021-04-10 13:43 UTC, wheejuni requested changes
우선 여기까지 구현하시느라 정말 수고 많으셨습니다. 👍 💯 
다만 `Action` 은 왜 존재해야 하는지 다소 공감이 안 가긴 합니다. 만약 `Card` 에 대한 이력 관리가 필요한 거라면 `Card` 그 자체에 대한 버전 관리를 하는 편이 더 좋아보이기는 합니다. 

현재 `Action` 에서 `Card` 의 제목을 관리하는 부분도 무척 어색하게 느껴집니다. 많은 경우에 연관관계는 PK로 관리되어야 하지, 테이블의 다른 상태값으로 관리하지 않기 때문입니다. 

여러모로 `Action` 이라는 오버 엔지니어링때문에 구현이 전반적으로 조금 복잡해진 느낌인데요, `Action` 과 계속 함께할 것인지를 진지하게 다시 고민해주세요. 

수고 많으셨습니다. 🥇

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/controller/ActionsController.java
> +    public ResponseEntity<Map<String, List<ActionsResponseDto>>> show() {
`Map` 을 감싼 `ResponseEntity` 를 리턴하는 것은 어색해 보입니다.
만약 `ActionsResponseDto` 를 품는 상위 개념의 리스폰스가 필요했다면 그 또한 DTO로 구상해 작성해주시는 방향이 맞지 않을까 생각되네요.

보통의 경우 아래와 같은 구성을 갖게 될 것 같습니다.

```java
public class ActionsResponse {

    private int actionsCount;
    private List<ActionsResponseDto> actionsResponse;

}
```

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/controller/CardsController.java
> +    public ResponseEntity<Card> create(@RequestBody HashMap<String, String> cardInfo) {
request를 위한 DTO도 설계해 주시는 것이 좋겠습니다.

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/controller/CardsController.java
> +    public ResponseEntity<Card> move(@PathVariable Long id, @RequestBody HashMap<String, String> cardInfo) {
`move` 라면 리스트 안에서 순서를 변경하는 로직이겠죠? 그런데 왜 `cardInfo` 파라메터가 필요했는지 조금 궁금합니다.

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/domain/Action.java
> +    private LocalDateTime createdDateTime;
JPA 기반으로 프로젝트를 진행하실 때 `@EnableJpaAuditing` 을 적용해보신 적이 있으실 텐데요,
Spring Data JDBC에도 같은 기능이 있습니다. 찾아보시고 적용해보시는 것도 도움이 되겠네요.

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/domain/Card.java
> +    public void update(HashMap<String, String> cardInfo) {
지난 프로젝트들에서 `Set`, `Map`, `List` 타입을 사용하는 경우 가급적 구현체보단 인터페이스에 의존하라는 리뷰를 드린 적이 있는 것 같습니다. 
특별히 `HashMap` 에 의존하셔야 할 필요가 없다면 이렇게 바꿔주시는 것이 어떨까요.

2021-04-10 13:43 UTC, wheejuni commented on backend/src/main/java/com/team06/todo/dto/ActionsResponseDto.java
> +    public ActionsResponseDto(Action action) {
여기에 `Builder` 패턴을 적용해보시는 시도는 어떨까요?

2021-04-12 11:09 UTC, ehdrhelr commented on backend/src/main/java/com/team06/todo/controller/CardsController.java
> +    public ResponseEntity<Card> move(@PathVariable Long id, @RequestBody HashMap<String, String> cardInfo) {
저희는 move 일 때 Card의 column_type을 변경해주는 로직입니다 ㅠㅡㅠ
처음 iOS와 협의에서 Card의 모든 데이터를 보내기주기로 해서 전체 카드정보를 받는 cardInfo를 사용했습니다.
오늘 협의에서는 변경된 부분만 받기로해서 RequestDto를 만들어 파라미터로 사용하면 될 것 같습니다~!

2021-04-12 13:01 UTC, ehdrhelr commented on backend/src/main/java/com/team06/todo/domain/Card.java
> +    public void update(HashMap<String, String> cardInfo) {
그부분 미처 생각하지 못했네요 ㅠㅠ.
cardInfo를 말씀해주신 Request DTO로 변환하였습니다.

2021-04-14 06:04 UTC, bong6981 commented on backend/src/main/java/com/team06/todo/controller/ActionsController.java
> +    public ResponseEntity<Map<String, List<ActionsResponseDto>>> show() {
말씀주신대로 ActionsResponse를 만들어 반환했습니다~!  json으로 반환할 때 키 값으로 string을 넣어줘야하는지 알았는데 getter의 메소드명으로 json 키 값이 들어오는 것을 알게되었습니다. 감사합니다 : )

2021-04-14 06:05 UTC, bong6981 commented on backend/src/main/java/com/team06/todo/controller/CardsController.java
> +    public ResponseEntity<Card> create(@RequestBody HashMap<String, String> cardInfo) {
request를 위한 DTO도 설계해 봤습니다. DTO를 처음 사용해볼 수 있어 많은 학습이 되었습니다~!

2021-04-14 06:07 UTC, bong6981 commented on backend/src/main/java/com/team06/todo/domain/Action.java
> +    private LocalDateTime createdDateTime;
현재@EnableJdbcAuditing 을 사용하여 @CreatedDate 로 자동 날짜 기능을 생성해주었습니다. 현재 학습 수준에서는  ActionType 과 String도 자동으로 불러오는 것을 찾지 못했습니다. ㅠㅠ

2021-04-14 06:08 UTC, bong6981 commented on backend/src/main/java/com/team06/todo/dto/ActionsResponseDto.java
> +    public ActionsResponseDto(Action action) {
말씀주신대로 Builder 패턴을 적용해보았는데 저희 둘 다 처음 써보는 패턴이라 맞게(?) 사용한지 확신이 안듭니다. 덕분에 새로운 패턴을 학습할 수 있었습니다~!

2021-04-14 06:24 UTC, bong6981 commented
> 우선 여기까지 구현하시느라 정말 수고 많으셨습니다. 👍 💯
> 다만 `Action` 은 왜 존재해야 하는지 다소 공감이 안 가긴 합니다. 만약 `Card` 에 대한 이력 관리가 필요한 거라면 `Card` 그 자체에 대한 버전 관리를 하는 편이 더 좋아보이기는 합니다.
> 
> 현재 `Action` 에서 `Card` 의 제목을 관리하는 부분도 무척 어색하게 느껴집니다. 많은 경우에 연관관계는 PK로 관리되어야 하지, 테이블의 다른 상태값으로 관리하지 않기 때문입니다.
> 
> 여러모로 `Action` 이라는 오버 엔지니어링때문에 구현이 전반적으로 조금 복잡해진 느낌인데요, `Action` 과 계속 함께할 것인지를 진지하게 다시 고민해주세요.
> 
> 수고 많으셨습니다. 🥇

- 말씀주신대로 Action에 대해서 고민을 했습니다 (오랜 시간 고민했는데도 답이 안나왔네요 ㅠㅠ) 
- 연관관계를 PK로 해야 한다는 부분을 저희가 놓쳤네요 ㅠㅠ 
- 히스토리를 관리하는 디자인 패턴도 찾아보았는데 별도의 테이블로 두어 관리하는 패턴도 있고 리뷰주신 방식도 (Card 안에서 리스트 형태로 관리하는 형식) 있는 것 같았습니다. 
- 다만 저희가 고민했던 건 Card안에서 관리했을 때 Actions의 생명주기가 Card에 의존하게 되어 Card를 delete를 했을 경우 Actions도 같이 사라지게 된다는 문제가 있었습니다. 
- 위의 대안으로 soft-delete를 적용해 보려 했었는데 이 부분에 대해서는 iOS분들과의 협의도 필요할 것 같아 아직 수정하지 않았습니다. 
- iOS분들과의 협의 후에 다음 코드리뷰 요청 드릴 때 수정드린 부분까지 같이 리뷰 요청 남기겠습니다. 

추가 변경, 문의 사항 
---

- iOS분들의 요청으로 (오고가는 데이터는 최소화 하라는 근거에 따라) colunmType을 Enum에서 int로 변경했습니다. (할 일(0), 하는 중(1), 마친 일(2)) 
- 해당 부분을 수정하면서 처음에는 데이터베이스에 Enum값으로 (TODO, IN_PROGRESS, DONE)으로 넣어주기 위해 int (요청) -> Enum(데이터베이스) -> int(응답) 으로 설정했으나 
- 데이터베이스에서 요청과 응답값(int)가 아닌 Enum으로 들어가면 통일성이 깨지는 것 같아 모두 int로 통일했습니다. 
- 요청-응답 값과 데이터베이스에 들어가는 것을 통일시켜 주는 것에 우선을 두어야 할지, 데이터베이스단에서 이해하기 쉽도록 Enum값으로 넣어주는 것이 좋을지 문의드립니다.  


덕분에 많은 부분을 학습할 수 있었습니다. 
감사합니다.!

2021-04-17 08:25 UTC, merged