[BE][Team-03]  todolist 구현
codesquad-members-2021/todo-list pull request #27
Opened 2021-04-13 07:18 UTC by ChoiGiSung

안녕하세요 team-03의 coco와 Kyu입니다.

## 구현내용  

![2021-04-13_17-43-49](https://user-images.githubusercontent.com/60220562/114502436-bf005780-9c66-11eb-9169-6b5b82b9160e.jpg)  

DB설계는 위와 같습니다.

* 배포링크 http://ec2-52-78-202-110.ap-northeast-2.compute.amazonaws.com:8080/todos  
* api링크   https://documenter.getpostman.com/view/15264844/TzCS6RsE
* 기본적인 crud기능은 만들었습니다.

* card와 log가 같은 애그리거트에 속한다고 생각해서 같은 도메인 안에 위치 시켰습니다.
log는 card의 상태가 변경되면 그때마다 생성됩니다.

## 궁금한 점

* 우선순위 구현은 생각해 봤는데, 우선순위라는 컬럼을 가지고 있게 하고
ios측에서 우선순위를 계산해 update하는 식으로 생각해 봤습니다.

card가 card들 사이에 들어가면 (이전 card의 우선순위 + 이후 card의 우선순위)/2.0
이런 식으로 로직을 생각해 봤습니다. 
이럴 경우 장기적으로 봤을 때 오류가 발생할 거 같아 화폐 번호와 비슷한 로직을 생각해 봤는데 적용이 쉽지 않아  리뷰어님의 생각은 어떠신지 궁금합니다.
* 화폐 번호 구현 링크 https://stackoverflow.com/a/49956113/10608

감사합니다.

2021-04-13 11:47 UTC, wheejuni requested changes
너무 어렵게 생각하지 마시고 단순하게 가시죠. 예를 들어 카드가 다섯 개 있다면...
우선순위 변경이 일어난다면 카드 다섯개의 `order` 칼럼이 모두 업데이트 되면 되는 것 아닐까요?
지금 단계에서 너무 복잡하고 다양한 제약사항을 고려한 구현을 시도하지 마시고, 쉽게 쉽게 갑시다. 

`Log`와 `Card` 가 같은 agg라면 agg root은 하나여야 합니다.
DDD의 개념을 적용하실 거라면 엄격히 적용하시고, 그럴 자신이 없다면 아예 적용하지 않는 것을 추천합니다. 
**하나의 레포지토리에선 하나의 엔티티만을 로드하는 것을 원칙으로 삼아주시기 바랍니다.**
둘이 같은 agg라면... 두 도메인 객체 모두에 접근해야 할 이유는 무엇이었을까요? 같은 agg가 아니었거나... 객체 그래프 탐색을 더 적극적으로 사용했어야 합니다. 

수고 많으셨습니다. 조금만 수정해보시죠. 👍

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardController.java
> +    Logger logger = LoggerFactory.getLogger(CardController.class);
ㅎㅎㅎ.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
> +    List<Log> findAllLog();
우리가 완전한 형태의 DDD를 하고 있진 않지만 `CardRepository` 에서 `Log` 객체를 꺼내오는 것은 너무 어색합니다.
`LogRepository` 의 구현을 고민해주셔야 할 것 같은데요.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardService.java
> +public class CardService {
메소드 이름을  CRUD action에 맞추지 말고 비즈니스 로직에 맞는 자연스러운 이름을 고민해 주시면 좋겠네요.
예를 들어 `.write()` 같은 경우에도 `.write()` 라는 이름보단 `.createCard()` 와 같은 이름이면 훨씬 자연스러울 것 같아요.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
> +    Iterable<Card> findByCardToNotDeleted();
왜 `Iterable` 을 리턴해야 하는지요? 뚜렷한 이유가 보이지 않습니다.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/TODoStatusPatternValidator.java
> +public class TODoStatusPatternValidator implements ConstraintValidator<ToDoStatusPattern, Enum<?>> {
우선 클래스 이름은 `ToDoStatusPatternValidator` 로 되어야겠죠.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/TODoStatusPatternValidator.java
> +    private Pattern pattern = Pattern.compile("TODO|DOING|DONE|DELETED");
조금 이해가 안 가는 부분이 있습니다.
이렇게 정형화되어 있는 경우의 수를 지닌다면.... 이 네 가지 경우의 수를 `enum` 으로 선언해버리면 굳이 이렇게 복잡한 밸리데이션 로직을 두지 않아도 될 텐데요. `enum` 을 고려하지 않으신 이유가 있나요?

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/model/Card.java
> +    }
이 `enum` 은 별도의 파일로 분리해주세요.
그리고 이 `enum` 을 적극적으로 사용할 수 있는 방법 고민해주세요.

앞선 밸리데이션 로직은 이 `Status` 에 `String` 필드 하나 추가하면 걷어낼 수 있는 로직입니다.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/dto/CardList.java
> +    private List<Card> done = new ArrayList<>();
`Builder` 패턴 적용하면 아래의 `.divide()`, `.sort()` 없이도 충분히 같은 로직을 구현할 수 있습니다.
`switch~case` 문은 앞으로도 가급적 사용을 **지양** 해 주시고 빌더 패턴으로 개선해보실 것을 강력히 권고합니다.

2021-04-13 11:47 UTC, wheejuni commented on backend/src/main/java/com/codeSquad/cocokyu/domain/model/Card.java
> +    private Status status;
Serialize/Deserialize 시에도 해당 `enum` 과 일치하는 문자열이 아니라면 Jackson에서 예외를 던질 텐데 굳이 밸리데이션까지 필요했을지는 잘 모르겠습니다..

2021-04-14 08:03 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardController.java
> +    Logger logger = LoggerFactory.getLogger(CardController.class);
앗.. 접근제어자를 안썼네요.. 사용 안해서 그냥 삭제했습니다!

2021-04-14 08:18 UTC, kyu-kim-kr commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardController.java
> +    Logger logger = LoggerFactory.getLogger(CardController.class);
ㅎㅎㅎ

2021-04-14 08:44 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/TODoStatusPatternValidator.java
> +public class TODoStatusPatternValidator implements ConstraintValidator<ToDoStatusPattern, Enum<?>> {
오타 수정했습니다!

2021-04-14 08:44 UTC, kyu-kim-kr commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
> +    List<Log> findAllLog();
Log가 Card에 종속되어있는데 CardRepository에서 Log 객체에서 꺼내는건 어색하다는 말씀이시죠??
LogRepository에서 부르도록 했습니다..!

2021-04-14 08:45 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
> +    Iterable<Card> findByCardToNotDeleted();
findAll이 Iterable로 줘서 따라 했었는데, List로 받는 게 맞을 거 같네요

2021-04-14 08:53 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/TODoStatusPatternValidator.java
> +    private Pattern pattern = Pattern.compile("TODO|DOING|DONE|DELETED");
enum에는 notblank가 적용이 안 된다고 봐서 새로운 어노테이션을 만들 생각만 했었네요.
밑에 말씀하신 것처럼  Serialize/Deserialize 시에 예외가 나는 것을 생각했으면 notnull만 붙이고 안 만들어도 되었을 텐데..

2021-04-14 08:57 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/model/Card.java
> +    }
분리했습니다!

2021-04-14 08:58 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/model/Card.java
> +    private Status status;
맞는 말씀이십니다.. notNull만 추가해 줬습니다.

2021-04-14 09:02 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
> +    List<Log> findAllLog();
`LogRepository `를 구현했습니다. DDD를 흉내 내보려 했는데 쉽지 않네요 ㅎㅎ
생명주기가 같다고 생각해서 같은 agg로 생각했었습니다.
log는 create_date_time으로 정렬하라는 요구사항을 어찌 해결할까 하다가 저질러버렸습니다.

2021-04-14 12:45 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/CardService.java
> +public class CardService {
수정했습니다!

2021-04-14 12:46 UTC, ChoiGiSung commented on backend/src/main/java/com/codeSquad/cocokyu/domain/dto/CardList.java
> +    private List<Card> done = new ArrayList<>();
공부 후 적용 시키겠습니다!

2021-04-17 08:26 UTC, merged