[BE][Team04 - Starve, Bibi, YJ, 쏭] Card Class, Repository, CRUD 구현
codesquad-members-2021/todo-list pull request #4
Opened 2021-04-08 14:10 UTC by bibi6666667

안녕하세요!
TodoList 미션을 진행하는 04번째 팀 [Starve, Bibi, YJ, 쏭] 입니다.

기본적인 Card Class, Repository, CRUD 구현을 마쳐, 첫 번째 PR을 보냅니다.

## 구현내용
1. BE단 API제공을 위한 기본 구조 (Controller, Domain, Repository, Service) 구현
2. 기본 CRUD 기능 구현
3. 본격적인 SQL과 AWS EC2 사용 전에 h2와 PostMan을 테스트 용도로 사용

## 구현하며 궁금했던 내용
- Card의 상태(todo / doing / done / deleted)를 나타내기 위해 Enum과 boolean 중 어떤 것을 사용할지 고민했습니다.
처음에는 간단히 모든 상태를 변수로 boolean을 사용했는데, 작성하다 보니 Card클래스의 메서드 중복 제거를 위해 Enum을 도입하자는 제안이 나왔습니다. 그런데,
1. 변수가 4개밖에 되지 않는데 굳이 Enum을 사용해 코드의 복잡도가 증가하는 것은 아닌지
2. Enum은 JSON형식으로 변환될 때  String이 되는 것 같은데, 이로 인해 iOS분들에게 괜한 혼란을 야기하는 것은 아닌지
이 부분이 고민이 되어 결국 boolean값으로 그대로 사용했습니다.
(대신 코드 중복 제거 문제는 메서드 분리로 해결했습니다.)
혹시 Enum과 boolean 중 어떤 자료형을 사용하는 게 더 바람직한지에 대해 괜찮으시다면 조언 부탁드립니다🙇‍♀️

미션 진행이 빠르지는 않지만, 지금까지 구현된 부분이라도 확인을 받고 싶어 조금 빠른 PR을 보냅니다.
부족한 코드지만 많은 피드백 부탁드립니다.
감사합니다! 😀

2021-04-10 02:09 UTC, wheejuni requested changes
초기 세팅을 잡느라 고생이 많으셨을 것 같네요. 수고 많으셨습니다. 👍 
우선 이 경우엔 `enum` 을 사용하는 것이 맞는 방향으로 생각됩니다. 
네 개라는 경우의 수는 결코 적지 않고요, 특히 상태 하나를 만들기 위해 나머지 세 개 변수의 상태를 바꿔야 하는 것은 비효율적인 것으로 생각됩니다. 

수고 많으셨습니다. 💯

2021-04-10 02:09 UTC, wheejuni commented on BE/src/main/java/codesquad/TodoList/TodoListApplication.java
> +		SpringApplication.run(TodoListApplication.class, args);
Tab 설정이 4 spaces 같군요. 특별한 목적이 없다면 4 spaces가 더 좋진 않을까 생각해봅니다.

2021-04-10 02:09 UTC, wheejuni commented on BE/src/main/java/codesquad/TodoList/domain/Card.java
> +    private boolean deleted;
절대로 좋은 구현이 아닙니다. 이렇게 할 바에야 `enum` 을 쓰는게 낫습니다.
클라이언트 개발자들도 그 편을 선호하지 않을까요? 이 카드의 상태를 특정하기 위해 네 개의 필드를 참조하는 것보다 사전에 합의된 `enum` 을 사용하는 편이 어떻게 봐도 더 좋은 구현일 것 같습니다.

2021-04-10 02:09 UTC, wheejuni commented on BE/src/main/java/codesquad/TodoList/service/CardService.java
> +    }
`enum` 설계해서 개선되면 이 메소드들도 다 걷어낼 수 있겠네요.

2021-04-12 08:40 UTC, bibi6666667 commented on BE/src/main/java/codesquad/TodoList/domain/Card.java
> +    private boolean deleted;
아 그렇군요! todo, doing, done, deleted 네 상태를 Status라는 enum클래스를 사용하도록 수정하겠습니다. 감사합니다😀👍!

2021-04-12 08:43 UTC, bibi6666667 commented on BE/src/main/java/codesquad/TodoList/service/CardService.java
> +    }
넵 enum 사용해서 이 메서드들은 삭제하겠습니다!

2021-04-12 08:48 UTC, Jiwon-JJW commented
안녕하세요! 
boolean 으로 표시되었던 status를 enum으로 변경 하여 재 PR요청을 드립니다!
다만, 작성하여 주신 리뷰에서 Tab 설정에 대한 말씀이 이해가 잘 되지 않는데, 혹시 다시 한 번 설명 부탁드려도 될까요?😅
리뷰 감사드립니다!

2021-04-17 08:26 UTC, merged