[BE] [team-9 아이작 & 노을] todo-list API 구현
codesquad-members-2021/todo-list pull request #43
Opened 2021-04-14 16:22 UTC by sanhee

`서버 API 정보` : https://documenter.getpostman.com/view/14857650/TzJpiKoE
`배포 URL` : http://13.209.62.240:8080/api/cards/todo

안녕하세요! 백엔드반 아이작&노을 입니다!

계획한 API 구현을 완료하게 되어 PR을 드리게 됐습니다!😀

## 궁금한점

1. 아래 긴 method 명이 올바른지 모르겠습니다, 사용자 입장에서는 Soft Delete를 몰라도 될 것 같아 `~AndDeletedFalse` 부분은 생략해도 괜찮을지 잘모르겠습니다.

```java
✨CardRepository.java

public List<Card> findAllByUserAndColumnTypeAndDeletedFalse(long user, String columnType); 

public Optional<Card> findByIdAndDeletedFalse(Long cardId); 
```

2.  현재 히스토리 기록을 가져오기 위해 Inner Join을 통해 구현했습니다. 
여기서 구한 히스토리 결과를 다른 객체(`HistoryWithCardTitle`)에서 갖고 있을지 아니면  HistoryRepository가 가져야할지 궁금합니다.

```java
public interface HistoryRepository extends CrudRepository<History, Long> {
    @Query("SELECT `card`.`title` as `card_title`, `history`.`action` as `action`, `history`.`DATE` as `date`, `history`.`from` as `from`, `history`.`to` as `to` FROM `history` " +
            "INNER JOIN `card` ON `history`.`CARD` = `card`.`ID` " +
            "INNER JOIN `user` ON `card`.`USER` = `user`.`ID` AND `user`.`ID` = :userId " +
            "ORDER BY `date` DESC")  //m :userId는 인자로 들어온 userId가 들어감
    public List<HistoryWithCardTitle> findAllByUserId(Long userId);
}
```

3. 현재 카드 생성/이동을 할 때 좌표 계산을  아래와 같이 구현했는데 어떤 문제점이 있을 수 있는지 궁금합니다.

 - `A =  2.0` `B = 3.0` `C= 4.0`  ➡C 가운데로 이동 ➡  `A =  2.0` `C= (A+B/2)` `B = 3.0`

2021-04-15 12:06 UTC, wheejuni requested changes
레포지토리는 `org.springframework.data` 에 정의된 인터페이스들을 상속한 것이라면 스프링 데이터의 쿼리 메소드 표준에 맞게 작명하는 것이 맞는 방향으로 생각됩니다. 따라서 지금 생각하시는 방향이 틀리지 않았다고 생각해요.

`HistoryRepository` 에 대한 의견은 인라인 코멘트로 남겨봤습니다. 참고해주세요. 👍 
조별 프로젝트 진행에 고생이 많으십니다~ 끝까지 힘내주세요! 💯

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/controller/ApiCardController.java
> +        return ApiResult.succeed(cardService.create(card.getTitle(), card.getContent(), card.getColumnType(), user));
`Service` 클래스에서 DTO 클래스들은 파라메터로 받아도 됩니다. 👍 
리팩토링이 가능할 것 같네요.

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/controller/GlobalApiExceptionHandler.java
> +    })
한줄로 써도 좋을 것 같습니다.

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/domain/ApiResult.java
> +public class ApiResult<T> {
좋은 설계입니다. 👍

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/domain/Card.java
> +    public static final double PRIORITY_STEP = 1.0;
어디서 사용되나요? 가급적이면.. 사용처와 가까이 위치하는것이 좋을 듯 하긴 한데요.

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/repository/CardRepository.java
> +    @Query("UPDATE `card` SET `deleted` = '1' WHERE (`id` = :cardId)")
`SET deleted = '1'` 로 입력하면... BOOLEAN 타입은 아닐 텐데요, 혹시 의도하신 설계인가요?

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/main/java/team9/todo/repository/HistoryRepository.java
> +    public List<HistoryWithCardTitle> findAllByUserId(Long userId);
별도의 레포지토리를 설계하시거나, 별도의 인터페이스로 분리하여 다중 상속을 이용해서 개선해주세요.
https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/#repositories.custom-implementations

처음엔 적용이 좀 어려울 수 있겠으나 _스프링 레포지토리 커스텀_ 과 같은 검색어로 적극 검색해보시면 레퍼런스가 아주 많이 나올 것으로 생각됩니다.

2021-04-15 12:06 UTC, wheejuni commented on BE/todo/src/test/java/team9/todo/controller/ApiCardControllerTest.java
> +    }
컨트롤러 테스트가 아닌 것 같네요. ㅜㅜ

2021-04-17 08:26 UTC, merged

2021-04-17 17:13 UTC, sanhee commented
@wheejuni 앗.. 브라이언 바쁘게 하다보니 리뷰 반영을 까먹고 아직 못했습니다 ㅠㅠㅠ

일요일에 한번 수정해보겠습니다 ㅠㅠㅠㅠ