Be 1
codesquad-members-2021/todo-list pull request #44
Opened 2021-04-14 16:53 UTC by d-h-k

# intro
안녕하세요! team10의 marco와 Dong입니다.

> 배포 링크 
http://13.209.4.14:8080/

> API 설명문서 
https://github.com/d-h-k/todo-list/wiki/API-%EB%A6%AC%EC%8A%A4%ED%8A%B8

# 기능구현 설명
- card의 생성, 삭제, 이동, 수정 기능을 구현하였습니다.
- 사용자의 action에 따른 history기능 또한 구현하였습니다.
- drag and drop 으로 카드 사이의 순서 변경시(우선순위 변경 기능) 은 구현하지 못했습니다.
- 위 기능들을 우선적으로 기능 구현을 진행했고, 예외처리는 추후 진행 예정입니다.

감사합니다.

2021-04-15 14:40 UTC, ksundong requested changes
안녕하세요! Marco & Dong!! 리뷰어 Dion입니다!
첫번째 프로젝트를 시작하신것을 진심으로 축하드리고, 정말 고생이 많으셨을 거라고 생각됩니다.
특히, 협업을 한다는 것은 또 다른 의미로 어려움이 있죠. 많이 많이 고생하시면 앞으로 현업에서도 도움이 많이되실겁니다.

- git을 좀 더 잘 다뤄주세요. gitignore 된 파일은 버전관리 되지 않아야 합니다.
- 포맷팅은 이제 필수입니다. 이 단계에서 지적받을 사항은 아니라고 생각해요.
- enum을 사용해주신 건 좋은데, 정작 필요한 위치에서 사용되지 않았네요.
- RESTful한 Url 설계에 대해서 고민해주세요. 다음 미션에서는 좀 더 나은 모습을 볼 수 있었으면 좋겠습니다.
- 변수 네이밍에 신경을 좀 더 써주세요.
- `@Transactional`에 대해서 학습해주시고, 적용해주세요.
- 개행을 의미단위로 하는 연습을 해주세요.

미션 수행하느라 고생많으십니다. 이제 얼마 안남았네요. 최선을 다해주세요~
궁금하시거나, 도움이 필요한 부분, 이해가 되지 않는 부분에 대해서 언제든 코멘트 남겨주세요.

**gitignore 되어야 하는 파일** 버전 관리 대상에서 `git rm --cached`로 제거해봐주세요~
시도해보시고 코멘트 남겨주세요~

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/.gitignore
> +/.idea/
gitignore가 정상적으로 처리되지 않은듯 보이네요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/.idea/vcs.xml
> +</project>
이 파일을 비롯해서... 각종 파일들... 꼭 확인해주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/build.gradle
> +	id 'org.springframework.boot' version '2.3.10.BUILD-SNAPSHOT'
왜 이 버전을 사용하셨나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/build.gradle
> +	maven { url 'https://repo.spring.io/snapshot' }
왜 이 저장소 경로가 필요했나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/build.gradle
> +	testImplementation 'org.springframework.boot:spring-boot-starter-test'}
```suggestion
dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'mysql:mysql-connector-java'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

```

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/settings.gradle
> +}
어디를 참고하고 요걸 넣어주셨나용?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/Action.java
> +}
👍

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/Category.java
> +}
enum을 적극적으로 사용해주셨네요~

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +@RequestMapping("/board")
board는 하나만 존재하나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public boolean create(@RequestBody BoardDto boardDto) {
DTO를 사용하는거 좋네요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public boolean create(@RequestBody BoardDto boardDto) {
근데 board를 만드는건가요? list를 만드는건가요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public List<Board> readAll() {
readAll말고 더 좋은 이름 고민해봐주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public List<Board> readTodos() {
Todo 보드는 하나 밖에 없지 않나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public List<Board> readDons() {
Dons(?)

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public Board readBoard(@PathVariable Long id) {
Board를 id로 불러올 수도 있나보군요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/LogController.java
> +    @GetMapping("/lists")
Q&A할 때 RESTful한 url 설계에 대해서 리뷰를 받은적이 없던건가요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/LogController.java
> +    @GetMapping("/lists/{limitNum}")
path가 아니라 query parameter로 받도록 수정해주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Board.java
> +    private int isDeleted = 0;
```suggestion
    @Column(value = "date_time")
    private LocalDateTime dateTime;
    
    @Column(value = "is_deleted")
    private int isDeleted = 0;
```
- 무슨 dateTime인가요? 확실하게 적어주세요.
- deleted인데 왜 int 타입인가요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Board.java
> +    private String category;
category는 Enum아니었나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Board.java
> +    }
왜 protected 기본 생성자를 만들어주셨나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Board.java
> +    }
```suggestion
    public int isDeleted() {
        return isDeleted;
    }
```

가급적이면 인텔리 제이 도구를 이용해서 getter 메서드를 만들어주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Board.java
> +    }
true가 적절하겠죠?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Log.java
> +    }
```suggestion
    protected Log() {
    }
```

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/domain/Log.java
> +    public Log(Board board, Action action){
```suggestion
    public Log(Board board, Action action) {
```

포매팅 신경써주세요~

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/dto/BoardDto.java
> +    }
💯

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/repository/BoardRepository.java
> +    @Query("select * from board where is_deleted like '%0' ")
`*` 의 사용은 절대 하지 말아주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/repository/BoardRepository.java
> +    @Query("select * from board where is_deleted like '%0' ")
왜 Like문을 사용해주셨나요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/repository/BoardRepository.java
> +    List<Board> findAll();
`@Override`가 누락된건 아닌가요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/repository/BoardRepository.java
> +@Repository
불필요한 애노테이션입니다.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/service/BoardService.java
> +        createLog(board,Action.ADD);
```suggestion
        createLog(board, Action.ADD);
```

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/service/BoardService.java
> +        return true;
true를 주는 것도 방법이고, 생성된 DTO를 반환해주는 것도 방법입니다!

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/service/BoardService.java
> +    }
`@Transactional`의 사용에 대해서 고민해주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/service/BoardService.java
> +    }
의미 단위로 개행을 통해 구분지어주세요.

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
> +    public List<Board> readAll() {
그리고 List를 그대로 반환하면 

```json
[
  {},
  {}
]
```

뭐 이런 형태가 되겠죠? 추가적으로 요구사항이 변한다면 breaking change가 발생할겁니다.

```json
{
  "boards": []
}
```

이런 형태라면 어떨까요? 
단순하게 count가 추가되어야 한다 정도의 요구사항이라면, 굳이 클라이언트를 수정하지 않아도 되겠죠?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
음... 왜 서로 다른가요?

2021-04-15 14:40 UTC, ksundong commented on backend/todolist/src/main/resources/static/index.html
> +</html>
설명 친절하네요.

2021-04-15 17:08 UTC, d-h-k commented on backend/todolist/src/main/resources/static/index.html
> +</html>
감사합니다

2021-04-15 17:10 UTC, d-h-k commented on backend/todolist/src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
todolist 라는 이름으로 DB를 생성하는게 맞는데, 프로젝트 초반에 이름을 혼동되도록 만들어서 사용중이였습니다. 해당부분 수정 진행하겠습니다.

2021-04-16 11:46 UTC, ksundong commented on backend/todolist/src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
네 DDL 스크립트를 작성해보는것도 추천해요~

2021-04-18 15:14 UTC, merged