[BE] [Team-08] ToDo-list 최종 구현
codesquad-members-2021/todo-list pull request #53
Opened 2021-04-15 15:40 UTC by jihye-woo

안녕하세요!! @Polynomeer(August) @jihye-woo(Woody) 입니다!!😀

### 개요

🔗 [API 배포 링크](http://54.180.218.17:8080/api/cards)
🔗 [API Document](https://github.com/dahun-lee-daji/todo-list/wiki/API-Document)

### 구현 내용
#### 1. Card에 대한 CRUD 구현
- CardRepository에서 Card를 읽어올 때, MySQL의 TINYINT와 Java의 boolean 타입이 맞지 않아서 직접 쿼리 작성

#### 2. History 조회 구현

#### 3. History 생성 로직 구현
- http 요청에 따라 히스토리 생성
- HistoryService에서 각 action에 대한 generate 메소드를 가지도록 구현
- Move와 Update는 소속 columnId의 변경 유무로 구분

감사합니다!!✨

2021-04-16 01:01 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
졸린 눈을 부비며 프로젝트를 진행했을 여러분의 모습을 떠올려보니 코드를 더 조심스럽게 읽게 되었습니다.

손봤으면 하는 부분은 모두 피드백으로 남겨 두었습니다.
큰 수정이 필요할 것 같진 않습니다. 💯 

수고하셨습니다~

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +        System.out.println(cardToUpdate.getColumnId());
`logger` 를 잘 선언했지만 `.println()` 을 쓰시는군요...

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +        } else {
여기 안에서 `return cardToUpdate` 를 하면, 아래 `else` 는 필요없겠죠?

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +    public String delete(@PathVariable Long cardId) {
가급적이면 REST API의 응답을 내릴땐, 순수 `String` 보다는 응답 래핑 객체를 만들어 내리는 것을 원칙으로 삼아 주세요.

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/dto/CardDto.java
> +    public CardDto(Long cardId, String title, String content, boolean isApp, String createdTime, Integer position, Long columnId) {
생성자에 담을 정보가 굉장히 많네요.
이런 경우 생성자를 `private` 정도로 가리고, 빌더 패턴이나 스태틱 팩토리 메소드 사용을 추천합니다.

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/dto/CardDto.java
> +    public static CardDto of(Card card) {
👍

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/repository/CardRepository.java
> +    @Query("SELECT CID, TITLE, CONTENT, `DATE`, POS, COLUMNID, AUTHOR, IF(`CARD`.ISAPP, 'true', 'false') as ISAPP from `CARD`")
`IF(`CARD`.ISAPP, 'true', 'false')` 이 부분은 불필요하지 않을까요?

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/repository/HistoryRepository.java
> +    List<History> findAll();
`.findAll` 은 이미 있는 메소드인데요? 왜 추가적으로 작성하셨나요?

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/service/CardService.java
> +    public CardDto delete(Long cardId) {
지웠는데 `CardDto` 가 리턴되는 건 좀 어색하지 않을까요?

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/service/CardService.java
> +    public Long update(Long cardId, CardDto cardToUpdate) {
지금은 도메인이 단순해서 크게 문제가 없었을 것 같은데 `UPDATE` 성 메소드엔 `@Transactional` 을 항상 붙여주세요.
도메인 객체가 조금만 더 복잡해지고, 관계 매핑이 들어가는 부분이 생기게 되면 문제에 부딪힐 수도 있습니다.

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/java/com/team08/todolist/service/HistoryService.java
> +        }
별도의 `enum` 으로 관리돼야 하지 않을까요?

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/resources/banner.txt
> +                                                              |__/
멋지네요;

2021-04-16 01:01 UTC, wheejuni commented on backend/src/main/resources/application.properties
> +spring.datasource.password=codesquad
아직은 괜찮지만 이걸 숨길 방법도 고민해야겠죠?
공개 레포에 암호 노출은 정말 정말 **위험합니다!**

2021-04-17 03:30 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +        System.out.println(cardToUpdate.getColumnId());
앗... 다음부터는 꼭 `logger`를 사용하겠습니다..🥲

2021-04-17 09:44 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/service/CardService.java
> +    public CardDto delete(Long cardId) {
delete한 이후 history(로그) 생성을 위해서 삭제된 CardDto 정보를 리턴해주었습니다..!

```java
// ApiCardController
CardDto cardDto = cardService.delete(cardId);
historyService.generateRemove(cardDto);
```

```java
// HistoryService에서 삭제 액션에 대한 History 생성 메소드
 public void generateRemove(CardDto cardDto) {
        History history = new History(null, "august17", cardDto.getTitle(), "remove", null, getColumnType(cardDto.getColumnId()), LocalDateTime.now());
        historyRepository.save(history);
    }
```

2021-04-17 09:47 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/service/CardService.java
> +    public CardDto delete(Long cardId) {
로직에 문제가 있는걸까요..?ㅠㅠ 
다른 방식으로 삭제 액션에 대한 히스토리 생성을 할 수 있도록 다시 한 번 더 생각해보겠습니당...!!🤔

2021-04-17 16:59 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/repository/HistoryRepository.java
> +    List<History> findAll();
CrudRepository에서 기본적으로 제공하는 findAll()의 리턴 타입이 `Iterable<T>`인데 리턴 타입을 `List<History>`로 바꾸기 위해서 오버라이드 해주었습니다!!

2021-04-17 17:03 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/repository/CardRepository.java
> +    @Query("SELECT CID, TITLE, CONTENT, `DATE`, POS, COLUMNID, AUTHOR, IF(`CARD`.ISAPP, 'true', 'false') as ISAPP from `CARD`")
int → boolean 치환하는 로직을 쿼리문에 넣지 않을 경우 아래와 같은 에러가 발생합니다ㅠㅠ
 
>There was an unexpected error (type=Internal Server Error, status=500).
>No converter found capable of converting from type [java.lang.Integer] to type [boolean]
>org.springframework.core.convert.ConverterNotFoundException: No converter found capable of >converting from type [java.lang.Integer] to type [boolean]


DB에서는 boolean 값이 따로 없고 TINYINT 밖에서 없어서 `isApp`의 데이터 타입을 int로 변경하거나 IF()로 쿼리문에서 변환 처리(int ➡️ boolean)하는 작업이 필요한 것 같습니다..ㅠㅠ

2021-04-18 08:11 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +        } else {
else를 없애고, 위 로직을 아래와 같이 메소드로 따로 분리했습니다..!
else가 없으니 훨씬 깔끔하네요👍 감사합니당
```java
private void generateUpdatedCardHistory(Long columnId, CardDto cardToUpdate) {
        if (columnId == cardToUpdate.getColumnId()) {
            historyService.generateUpdate(cardToUpdate);
            return;
        }
        historyService.generateMove(columnId, cardToUpdate);
    }
```

2021-04-18 08:13 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +        System.out.println(cardToUpdate.getColumnId());
아래와 같이 수정했습니다...! 휴우..🥲
```java
 logger.debug("Card to update has column id {}.", columnId);
 logger.debug("Updated card info has column id {}.", columnId);    
```

2021-04-18 08:48 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
> +    public String delete(@PathVariable Long cardId) {
말씀하신대로 응답 래핑 용도로 ApiResponse라는 클래스를 아래와 같이 만들었습니다!!
String 타입 뿐만 아니라 응답에 대한 모든 요청을 ApiResponse 객체에 담아서 보내도록 수정하였습니다..!

```java
public class ApiResponse<T> {

    private final T response;

    private final String message;

    private ApiResponse(T response, String message) {
        this.response = response;
        this.message = message;
    }
// ...
}
```
클라이언트로 응답을 보내는 형식에 통일성이 생긴 느낌이라 개인적으로는 기분이 좋네요..😃 
혹시 문제되는 부분이 있으면!! 말씀해주시면 감사드리겠습니당..!😅

2021-04-18 09:30 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/dto/CardDto.java
> +    public CardDto(Long cardId, String title, String content, boolean isApp, String createdTime, Integer position, Long columnId) {
안그래도 생성자 파라미터에 데이터들이 늘어나면서 데이터 순서가 헷갈리기 시작하더라구요..😂

그래서 말씀하신대로 엔티티의 생성자는 `private`으로 설정하고, Card와 CardDto 내부에는 `Builder`를 만들어서 빌더를 통해 객체를 생성할 수 있도록 수정하였습니다!!

```java
 // CardDto
    public static Builder build(Long cardId, Integer position, Long columnId) {
        return new Builder(cardId, position, columnId);
    }

    static public class Builder {
        private Long cardId;
        private String title = "no title";
        private String content = "no contents";
        private boolean isApp = true;
        private LocalDateTime createdDateTime = LocalDateTime.now();
        private Integer position;
        private Long columnId;

        private Builder(Long cardId, Integer position, Long columnId) {
            this.cardId = cardId;
            this.position = position;
            this.columnId = columnId;
        }
   // ...
    }
```
파라미터 순서를 생각하지 않고 데이터를 집어넣어도 된다는게 제일 행복하네요..✨ 감사합니당👍👍
```java
// 빌더를 사용해서 CardDto 객체 생성
public static CardDto of(Card card) {
        return CardDto.build(card.getCid(), card.getPos(), card.getColumnId())
                .title(card.getTitle())
                .content(card.getTitle())
                .isApp(card.isApp())
                .createdDateTime(card.getDate())
                .build();
    }
```

2021-04-18 09:46 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/service/CardService.java
> +    public Long update(Long cardId, CardDto cardToUpdate) {
Transactional 처리를 안해주었네요ㅠㅠ 

서비스 레이어에서
1. `UPATE` 성 (INSERT, UPDATE, DELETE에 해당하는 메소드) 메소드의 경우에는 @Transactional을,
2. `SELECT`(단순 조회)를 위한 메소드에는 @Transactional(readOnly=true)를 붙여 주었습니다!

2021-04-18 09:58 UTC, jihye-woo commented on backend/src/main/java/com/team08/todolist/service/HistoryService.java
> +        }
```java
public enum ColumnType {

    TODO("ToDo"),
    DOING("Doing"),
    DONE("Done");
 // ...
}
```

사실 처음에는 enum을 사용하게 되면 column 타입 처리와 관련한 코드들이 지금보다 늘어나게 되어서 불필요하다고 생각을 했었습니다...!😅

근데 다시 생각을 해보니 `ColumnType` enum 클래스로 column 타입 처리와 관련한 책임을 분리해서 서비스 레이어에 불필요한 로직을 제거한다고 생각하니 바로 만들어주어야 겠다는 생각이 들었습니다..!👀 (레퍼런스 : 디온)

덕분에 enum의 효용성에 대해서도 더 생각해보게 되었네용 감사합니당👍👍

2021-04-18 10:03 UTC, jihye-woo commented on backend/src/main/resources/application.properties
> +spring.datasource.password=codesquad
ㅇ앗... 그렇군요 아무 생각 없이 넘어갔는데 다시 생각해보니, "비밀번호 여기있습니다~ 여기 보세요~ "이런 느낌이군요..😅
감사합니다!!👍👍

2021-04-19 12:06 UTC, wheejuni commented on backend/src/main/resources/application.properties
> +spring.datasource.password=codesquad
좋은 느낌이네요 ㅋㅋ

2021-04-19 12:06 UTC, merged